baseURL = "https://www.noisedh.cn"
languageCode = "zh-CN"
title = "Noise导航 & 收录值得珍藏的网站"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "Noise导航"
    description   = "Noise导航 & 收录值得珍藏的网站"
    siteurl       = "./"
    about         = "https://www.yuque.com/shenweiyan/cookbook/webstack-hugo"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"
    enablePreLoad = true		    		        # 网站完全打开前预加载的动画
    textPreLoad   = "Noise导航 & 收录值得珍藏的网站"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    logosPath     = "assets/images/logos"				# 网站每个导航地址logo存放地址

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "https://cdn.jsdelivr.net/gh/rcy1314/tuchuang@main/NV/236811b8721adee31505c753684160e8.5kjldruyrz40.gif"		#搜索部分浅色背景图
    searchImageD      = "https://cdn.jsdelivr.net/gh/rcy1314/tuchuang@main/NV/236811b8721adee31505c753684160e8.5kjldruyrz40.gif"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bioitee-expand-light.png"
    logoExpandDark    = "assets/images/bioitee-expand-dark.png"
    logoCollapseLight = "assets/images/logo-collapse-light.png"
    logoCollapseDark  = "assets/images/logo-collapse-dark.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站收录值得珍藏的网站，欢迎访问使用'
